server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/userinfo/**
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  mapper-locations: classpath*:com/**/mapper/*.xml

gateway:
  shouldSkipUrls:
    - /oauth/**
    - /user/**