spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/userinfo/**

gateway:
  shouldSkipUrls:
    - /oauth/**
    - /user/**

#knife4j:
#  # 开启增强配置
#  enable: true
#  # 是否生产环境 默认否;生产环境配置为true，将无法访问文档
#  production: false
#  basic:
#    enable: true
#    # Basic认证用户名
#    username: admin
#    # Basic认证密码
#    password: 123456