spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-com.dm.service
          predicates:
            - Path=/user/**,/userinfo/**

gateway:
  shouldSkipUrls:
    - /oauth/**
    - /user/**